/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État du serveur */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            transcriber: string;
                            llm: string;
                            email: string;
                            /** @description Adresse utilisée dans les liens envoyés aux clients */
                            publicUrl: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Créer un compte artisan (et se connecter) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CredentialsInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Se connecter (pose le cookie de session `sid`) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CredentialsInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Se déconnecter */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Utilisateur connecté */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil entreprise de l'artisan (mentions légales des devis) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Company"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifier le profil entreprise (champs partiels) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompanyUpdateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Company"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister ses clients */
        get: {
            parameters: {
                query?: {
                    /** @description Filtre sur le nom ou l'e-mail */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"][];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Créer un client */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientCreateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un client */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Supprimer un client (refusé s'il a des devis) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supprimé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": null;
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Modifier un client (champs partiels) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientUpdateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister ses devis (du plus récent au plus ancien) */
        get: {
            parameters: {
                query?: {
                    /** @description Filtrer par statut */
                    status?: components["schemas"]["QuoteStatusInput"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteSummary"][];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Créer un devis (brouillon), pour un client existant ou nouveau
         * @description Le numéro (D-AAAA-NNNN), la durée de validité et les conditions de paiement par défaut viennent du profil entreprise s'ils ne sont pas fournis.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QuoteCreateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDetail"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un devis : client, lignes, totaux, points manquants, historique */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDetail"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Supprimer un devis (brouillon ou prêt uniquement) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supprimé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": null;
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Modifier les infos du devis (brouillon ou prêt uniquement)
         * @description Un devis « prêt » modifié repasse en brouillon.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QuoteUpdateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDetail"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/quotes/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Changer le statut à la main (draft, ready, accepted, declined)
         * @description Passer en `ready` exige un devis complet : sinon 409 `quote_incomplete` avec la liste dans `details.issues`. Les autres statuts (envoyé, consulté, à relancer, expiré) sont posés automatiquement.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StatusChangeInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDetail"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Envoyer le devis au client (il doit être « prêt à envoyer »)
         * @description Envoie un e-mail au client avec le lien du devis (bouton « Voir le devis »), réponse vers l'artisan, puis passe le devis en « envoyé » : il n'est plus modifiable et son lien public (`publicUrl`) devient accessible. Si l'e-mail échoue : 502 `email_failed` et le devis reste « prêt ».
         *
         *     `byEmail: false` : aucun e-mail, l'artisan partage le lien lui-même (SMS, WhatsApp...).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendQuoteInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDetail"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renvoyer l'e-mail d'un devis déjà envoyé
         * @description Pour un devis envoyé, consulté ou à relancer : renvoie le même e-mail à l'adresse actuelle du client (corriger l'adresse sur la fiche client si besoin). Le statut et la date du devis ne changent pas.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDetail"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aperçu du document client (à tout moment, sans suivi) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDocument"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ajouter une ligne en fin de devis */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LineCreateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDetail"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/lines/{lineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Supprimer une ligne */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    lineId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDetail"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Modifier une ligne (champs partiels) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    lineId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LineUpdateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDetail"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/quotes/{id}/lines/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Réordonner les lignes */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LineOrderInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDetail"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/clips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les dictées d'un devis */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Clip"][];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Envoyer une dictée audio (talkie-walkie) ou un segment d'écoute passive
         * @description Corps : le fichier **WAV** brut (PCM 16 bits ou flottant 32 bits, toute fréquence), avec `Content-Type: audio/wav`. La dictée est transcrite puis analysée en tâche de fond : les lignes extraites s'ajoutent au devis. Suivre l'avancement via `GET /api/quotes/{id}` (champ `clips`) ou passer `wait=true` pour attendre le résultat.
         *
         *     Hors connexion : générer un `clientClipId` (UUID) sur le téléphone. Un renvoi du même clip renvoie le clip existant (200) au lieu d'en créer un second.
         *
         *     Écoute passive : la visite est enregistrée en continu et envoyée par segments (`kind=passive`, `MAX_CLIP_SECONDS` chacun au plus). Le LLM sait alors qu'il lit une conversation. `estimatedReadyAt` donne la fin de traitement estimée.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Identifiant du clip généré par le téléphone */
                    clientClipId?: string;
                    /** @description Date de l'enregistrement (ISO 8601) */
                    recordedAt?: string;
                    /** @description dictation (défaut) ou passive (segment d'écoute passive) */
                    kind?: "dictation" | "passive";
                    /** @description true = attendre la fin du traitement (2 min max) */
                    wait?: "true" | "false";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Clip déjà reçu, ou traitement terminé (wait=true) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Clip"];
                    };
                };
                /** @description Clip reçu, traitement en cours */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Clip"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/clips/{clipId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'une dictée : statut, transcription, points manquants */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    clipId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Clip"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/clips/{clipId}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Réécouter une dictée (WAV mono 24 kHz) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    clipId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/clips/{clipId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Relancer le traitement d'une dictée en échec
         * @description Si la transcription avait réussi, seule l'analyse par le LLM est refaite.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    clipId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Clip"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les photos d'un devis */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Photo"][];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Ajouter une photo de chantier
         * @description Corps : l'image brute (JPEG, PNG ou WebP) avec son `Content-Type`. Le type est vérifié sur le contenu du fichier. Réduire la photo sur le téléphone avant l'envoi (ex. 1600 px de large).
         *
         *     Hors connexion : générer un `clientPhotoId` (UUID) sur le téléphone. Un renvoi de la même photo renvoie la photo existante (200) au lieu d'en créer une seconde.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Identifiant de la photo généré par le téléphone */
                    clientPhotoId?: string;
                    /** @description Date de la prise de vue (ISO 8601) */
                    takenAt?: string;
                    /** @description Légende */
                    caption?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Photo déjà reçue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Photo"];
                    };
                };
                /** @description Photo ajoutée */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Photo"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/photos/{photoId}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fichier image d'une photo */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{id}/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Supprimer une photo */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supprimée */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": null;
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Modifier la légende ou la visibilité pour le client */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PhotoUpdateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Photo"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/public/quotes/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ouvrir le devis (page client)
         * @description La première ouverture fait passer le devis de « envoyé » à « consulté ».
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Secret du lien public du devis */
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDocument"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/quotes/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accepter le devis (bon pour accord) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Secret du lien public du devis */
                    token: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AcceptQuoteInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDocument"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/quotes/{token}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refuser le devis */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Secret du lien public du devis */
                    token: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeclineQuoteInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDocument"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/quotes/{token}/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photo partagée avec le client */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Secret du lien public du devis */
                    token: string;
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/quotes/{token}/pixel.gif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pixel de suivi de l'e-mail
         * @description Image invisible insérée dans l'e-mail : note « e-mail ouvert » dans l'historique, à titre indicatif (Apple Mail précharge les images). Répond toujours l'image, même pour un lien inconnu.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CredentialsInput: {
            /**
             * Format: email
             * @description Adresse e-mail de connexion
             */
            email: string;
            /** @description 8 caractères minimum */
            password: string;
        };
        CompanyUpdateInput: {
            /** @description Nom commercial ou raison sociale */
            name?: string;
            /** @description Forme juridique : EI, SARL, SAS... (+ capital le cas échéant) */
            legalForm?: string;
            address?: string;
            phone?: string;
            email?: string;
            siret?: string;
            /** @description N° de TVA intracommunautaire */
            vatNumber?: string;
            /** @description Franchise en base de TVA (auto-entrepreneur) : pas de TVA sur les devis */
            vatExempt?: boolean;
            /** @description Assureur décennale */
            insurerName?: string;
            insurancePolicyNumber?: string;
            /** @description Couverture géographique de l'assurance */
            insuranceCoverage?: string;
            defaultValidityDays?: number;
            /** @description Conditions de paiement par défaut */
            defaultPaymentTerms?: string;
        };
        ClientCreateInput: {
            name: string;
            email?: string | "";
            phone?: string;
            address?: string;
        };
        ClientUpdateInput: {
            name?: string;
            email?: string | "";
            phone?: string;
            address?: string;
        };
        /**
         * @description draft = brouillon, ready = prêt à envoyer, sent = envoyé, viewed = consulté, follow_up = à relancer, accepted = accepté, declined = refusé, expired = expiré
         * @enum {string}
         */
        QuoteStatusInput: "draft" | "ready" | "sent" | "viewed" | "follow_up" | "accepted" | "declined" | "expired";
        LineCreateInput: {
            description: string;
            room?: string;
            quantity: number;
            /**
             * @description u, m2, ml, m3, h, jour, forfait, kg, l, ens
             * @enum {string}
             */
            unit: "u" | "m2" | "ml" | "m3" | "h" | "jour" | "forfait" | "kg" | "l" | "ens";
            unitPriceCents?: number | null;
            /**
             * @description Taux de TVA en points de base : 2000 = 20 %, 1000 = 10 %, 550 = 5,5 %, 0
             * @default 2000
             */
            vatRateBp: 2000 | 1000 | 550 | 0;
        };
        LineUpdateInput: {
            description?: string;
            room?: string;
            quantity?: number;
            /**
             * @description u, m2, ml, m3, h, jour, forfait, kg, l, ens
             * @enum {string}
             */
            unit?: "u" | "m2" | "ml" | "m3" | "h" | "jour" | "forfait" | "kg" | "l" | "ens";
            unitPriceCents?: number | null;
            /** @description Taux de TVA en points de base : 2000 = 20 %, 1000 = 10 %, 550 = 5,5 %, 0 */
            vatRateBp?: 2000 | 1000 | 550 | 0;
        };
        PhotoUpdateInput: {
            caption?: string;
            visibleToClient?: boolean;
        };
        SendQuoteInput: {
            /**
             * @description true : e-mail au client (par défaut) ; false : lien seul, partagé par l'artisan
             * @default true
             */
            byEmail: boolean;
        } | null;
        AcceptQuoteInput: {
            /** @description Nom et prénom du client : vaut signature */
            name: string;
            message?: string;
        };
        DeclineQuoteInput: {
            name?: string;
            /** @description Motif du refus (facultatif) */
            message?: string;
        };
        QuoteCreateInput: {
            /**
             * Format: uuid
             * @description Client existant...
             */
            clientId?: string;
            /** @description ...ou nouveau client créé en même temps que le devis */
            client?: components["schemas"]["ClientCreateInput"];
            title?: string;
            siteAddress?: string;
            validityDays?: number;
            /**
             * Format: date
             * @description AAAA-MM-JJ
             */
            startDate?: string | null;
            duration?: string;
            paymentTerms?: string;
            notes?: string;
        };
        QuoteUpdateInput: {
            /** Format: uuid */
            clientId?: string;
            title?: string;
            siteAddress?: string;
            validityDays?: number;
            /**
             * Format: date
             * @description AAAA-MM-JJ
             */
            startDate?: string | null;
            duration?: string;
            paymentTerms?: string;
            notes?: string;
        };
        StatusChangeInput: {
            /** @description draft, ready, accepted ou declined */
            status: components["schemas"]["QuoteStatusInput"];
        };
        LineOrderInput: {
            /** @description Tous les identifiants de lignes, dans le nouvel ordre */
            lineIds: string[];
        };
        Error: {
            /** @description Code d'erreur stable, à utiliser côté front */
            error: string;
            /** @description Message lisible, en français */
            message: string;
            details?: unknown;
        };
        User: {
            /** Format: uuid */
            id: string;
            email: string;
            /** @description Date ISO 8601 */
            createdAt: string;
        };
        Company: {
            /** @description Nom commercial ou raison sociale */
            name: string;
            /** @description Forme juridique : EI, SARL, SAS... (+ capital le cas échéant) */
            legalForm: string;
            address: string;
            phone: string;
            email: string;
            siret: string;
            /** @description N° de TVA intracommunautaire */
            vatNumber: string;
            /** @description Franchise en base de TVA (auto-entrepreneur) : pas de TVA sur les devis */
            vatExempt: boolean;
            /** @description Assureur décennale */
            insurerName: string;
            insurancePolicyNumber: string;
            /** @description Couverture géographique de l'assurance */
            insuranceCoverage: string;
            /** @description Durée de validité par défaut des devis, en jours */
            defaultValidityDays: number;
            /** @description Conditions de paiement par défaut */
            defaultPaymentTerms: string;
            /** @description Date ISO 8601 */
            updatedAt: string;
        };
        Client: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            phone: string;
            /** @description Adresse de facturation */
            address: string;
            /** @description Date ISO 8601 */
            createdAt: string;
            /** @description Date ISO 8601 */
            updatedAt: string;
        };
        /**
         * @description draft = brouillon, ready = prêt à envoyer, sent = envoyé, viewed = consulté, follow_up = à relancer, accepted = accepté, declined = refusé, expired = expiré
         * @enum {string}
         */
        QuoteStatus: "draft" | "ready" | "sent" | "viewed" | "follow_up" | "accepted" | "declined" | "expired";
        QuoteLine: {
            /** Format: uuid */
            id: string;
            /** @description Ordre d'affichage, à partir de 1 */
            position: number;
            description: string;
            /** @description Pièce concernée (cuisine, salle de bain...) */
            room: string;
            quantity: number;
            /**
             * @description u, m2, ml, m3, h, jour, forfait, kg, l, ens
             * @enum {string}
             */
            unit: "u" | "m2" | "ml" | "m3" | "h" | "jour" | "forfait" | "kg" | "l" | "ens";
            /** @description Unité à afficher (m², ml...) */
            unitLabel: string;
            /** @description Prix unitaire HT en centimes, null = à renseigner */
            unitPriceCents: number | null;
            vatRateBp: number;
            /** @description Total HT de la ligne (centimes) */
            totalHtCents: number | null;
            /**
             * @description Ligne saisie à la main ou issue d'une dictée
             * @enum {string}
             */
            source: "manual" | "dictation";
            /**
             * Format: uuid
             * @description Dictée dont la ligne est issue
             */
            clipId: string | null;
            /** @description Date ISO 8601 */
            createdAt: string;
            /** @description Date ISO 8601 */
            updatedAt: string;
        };
        QuoteEvent: {
            /** Format: uuid */
            id: string;
            /** @description created, status_changed... */
            type: string;
            /** @enum {string} */
            actor: "artisan" | "client" | "system";
            fromStatus: components["schemas"]["QuoteStatus"] | null;
            toStatus: components["schemas"]["QuoteStatus"] | null;
            /** @description Date ISO 8601 */
            createdAt: string;
        };
        Clip: {
            /** Format: uuid */
            id: string;
            /** @description Identifiant généré par le téléphone */
            clientClipId: string | null;
            /**
             * @description dictation = talkie-walkie, passive = segment d'une écoute passive
             * @enum {string}
             */
            kind: "dictation" | "passive";
            /**
             * @description pending → transcribing → transcribed → extracting → done, ou failed
             * @enum {string}
             */
            status: "pending" | "transcribing" | "transcribed" | "extracting" | "done" | "failed";
            statusLabel: string;
            durationMs: number;
            /** @description Texte transcrit (null tant que la transcription n'est pas faite) */
            transcript: string | null;
            /** @description Informations manquantes relevées par l'analyse (quantités, dimensions...) */
            warnings: string[];
            /** @description Cause de l'échec, si status = failed */
            error: string | null;
            /** @description Nombre de lignes ajoutées au devis par cette dictée */
            lineCount: number;
            /** @description Fin de traitement estimée (file de transcription puis analyse) ; null une fois terminé */
            estimatedReadyAt: string | null;
            /** @description Date ISO 8601 */
            recordedAt: string;
            /** @description Date ISO 8601 */
            createdAt: string;
            /** @description Date ISO 8601 */
            updatedAt: string;
        };
        Photo: {
            /** Format: uuid */
            id: string;
            /** @description Identifiant généré par le téléphone */
            clientPhotoId: string | null;
            /** @description image/jpeg, image/png ou image/webp */
            mimeType: string;
            sizeBytes: number;
            /** @description Légende libre */
            caption: string;
            /** @description Affichée au client sur la page du devis ; sinon note interne de l'artisan (par défaut) */
            visibleToClient: boolean;
            /** @description Date de la prise de vue */
            takenAt: string;
            /** @description URL du fichier image (même origine, cookie de session requis) */
            url: string;
            /** @description Date ISO 8601 */
            createdAt: string;
            /** @description Date ISO 8601 */
            updatedAt: string;
        };
        QuoteTotals: {
            /** @description Total HT (centimes) */
            totalHtCents: number;
            vatBreakdown: {
                vatRateBp: number;
                /** @description Base HT (centimes) */
                baseHtCents: number;
                /** @description Montant de TVA (centimes) */
                vatCents: number;
            }[];
            /** @description Total TVA (centimes) */
            totalVatCents: number;
            /** @description Total TTC (centimes) */
            totalTtcCents: number;
            /** @description Lignes sans prix : si > 0, les totaux sont partiels */
            unpricedLineCount: number;
            vatExempt: boolean;
            /** @description Mention à imprimer si l'entreprise est en franchise de TVA */
            vatMention: string | null;
        };
        /** @description Réponse du client depuis la page publique */
        QuoteResponse: {
            /** @enum {string} */
            decision: "accepted" | "declined";
            /** @description Nom saisi par le client (vaut signature pour une acceptation) */
            name: string;
            message: string;
            /** @description Date ISO 8601 */
            at: string;
        };
        /** @description Le devis tel que le client le voit, avec les mentions légales */
        QuoteDocument: {
            number: string;
            title: string;
            status: components["schemas"]["QuoteStatus"];
            statusLabel: string;
            /** @description Date du devis : date d'envoi (ou de création pour un aperçu) */
            issuedAt: string;
            /** @description Date ISO 8601 */
            validUntil: string;
            validityDays: number;
            siteAddress: string;
            startDate: string | null;
            duration: string;
            paymentTerms: string;
            company: {
                name: string;
                legalForm: string;
                address: string;
                phone: string;
                email: string;
                siret: string;
                vatNumber: string;
                insurerName: string;
                insurancePolicyNumber: string;
                insuranceCoverage: string;
            };
            client: {
                name: string;
                email: string;
                phone: string;
                address: string;
            };
            lines: {
                position: number;
                description: string;
                room: string;
                quantity: number;
                unitLabel: string;
                /** @description Prix unitaire HT (centimes) */
                unitPriceCents: number | null;
                vatRateBp: number;
                /** @description Total HT de la ligne (centimes) */
                totalHtCents: number | null;
            }[];
            totals: components["schemas"]["QuoteTotals"];
            photos: {
                /** Format: uuid */
                id: string;
                caption: string;
                url: string;
            }[];
            response: components["schemas"]["QuoteResponse"] | null;
            /** @description Afficher les boutons Accepter / Refuser */
            canRespond: boolean;
            /** @description Aperçu de l'artisan (aucun suivi, pas de réponse possible) */
            preview: boolean;
        };
        QuoteDetail: {
            /** Format: uuid */
            id: string;
            /** @description Numéro chronologique : D-2026-0001 */
            number: string;
            status: components["schemas"]["QuoteStatus"];
            /** @description Libellé du statut, en français */
            statusLabel: string;
            title: string;
            /** @description Adresse du chantier */
            siteAddress: string;
            validityDays: number;
            /** @description Fin de validité (calculée à partir de l'envoi) */
            validUntil: string | null;
            /** @description Date de début des travaux (AAAA-MM-JJ) */
            startDate: string | null;
            /** @description Durée estimée des travaux, texte libre */
            duration: string;
            paymentTerms: string;
            notes: string;
            /** @description Date ISO 8601 */
            sentAt: string | null;
            /** @description Date ISO 8601 */
            createdAt: string;
            /** @description Date ISO 8601 */
            updatedAt: string;
            client: components["schemas"]["Client"];
            lines: components["schemas"]["QuoteLine"][];
            totals: components["schemas"]["QuoteTotals"];
            /** @description Ce qui manque pour passer le devis en « prêt » (vide = complet) */
            issues: string[];
            /** @description Statuts que l'artisan peut poser via POST /status */
            allowedTransitions: components["schemas"]["QuoteStatus"][];
            /** @description Dictées du devis et leur état de traitement */
            clips: components["schemas"]["Clip"][];
            /** @description Photos de chantier du devis */
            photos: components["schemas"]["Photo"][];
            /** @description Lien de la page client (null tant que le devis n'est pas envoyé) */
            publicUrl: string | null;
            response: components["schemas"]["QuoteResponse"] | null;
            /** @description Première ouverture de la page par le client */
            viewedAt: string | null;
            events: components["schemas"]["QuoteEvent"][];
        };
        QuoteSummary: {
            /** Format: uuid */
            id: string;
            number: string;
            status: components["schemas"]["QuoteStatus"];
            statusLabel: string;
            title: string;
            client: {
                /** Format: uuid */
                id: string;
                name: string;
            };
            /** @description Total HT (centimes) */
            totalHtCents: number;
            /** @description Total TTC (centimes) */
            totalTtcCents: number;
            unpricedLineCount: number;
            lineCount: number;
            /** @description Date ISO 8601 */
            sentAt: string | null;
            /** @description Date ISO 8601 */
            createdAt: string;
            /** @description Date ISO 8601 */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
